exports.events = {
	USER_JOINED_CHAT_EVENT: "USER_JUSER_JOINED_CHAT_EVENTOIN_CHAT_EVENT",
	USER_LEFT_CHAT_EVENT: "USER_LEFT_CHAT_EVENT",
	NEW_CHAT_MESSAGE_EVENT: "NEW_CHAT_MESSAGE_EVENT",
	USER_START_TYPING_MESSAGE_EVENT: "USER_START_TYPING_MESSAGE_EVENT",
	USER_STOP_TYPING_MESSAGE_EVENT: "USER_STOP_TYPING_MESSAGE_EVENT"
}